name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-terminal
      - run: pip install termynal
      - run: pip install mkdocs-git-revision-date-plugin
      - run: ls .
      - run: cd ./document && mkdocs build
      - run: cd ./document && mkdocs gh-deploy --force
